version: '3'
services:
    web: 
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
    php:
        build:
          context: .
          dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 33066:3306
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8081:80
        environment:
          - PMA_HOST=mysql
          - PMA_PORT=3306
          - PMA_USER=tutorial
          - PMA_PASSWORD=secret
volumes:
    mysqldata: {}